# MCP Security Framework Configuration
# This file contains the default security configuration for the framework

# Identity Management Configuration
identity_management:
  require_authentication: true
  require_authorization: true
  certificate_validation: true
  identity_proof_required: true
  session_timeout: 3600  # seconds
  max_sessions_per_agent: 5
  session_cleanup_interval: 300  # seconds

# Trust Calculation Configuration
trust_calculation:
  decay_factor: 0.95  # Trust decay per hour
  min_events: 5  # Minimum events for reliable trust score
  window_size: 100  # Sliding window size for event analysis
  sybil_threshold: 0.8  # Threshold for sybil attack detection
  collusion_threshold: 0.7  # Threshold for collusion detection
  trust_update_interval: 60  # seconds
  max_trust_events: 1000  # Maximum events to store per agent

# MCP Integration Configuration
mcp_integration:
  server_security:
    require_authentication: true
    require_authorization: true
    tool_verification: true
    context_encryption: true
    connection_timeout: 30  # seconds
    max_retries: 3
  
  tool_verification:
    enabled: true
    signature_verification: true
    capability_verification: true
    sandbox_execution: true
    static_analysis: true
    dynamic_analysis: false
    verification_timeout: 60  # seconds
  
  discovery:
    auto_discover: true
    network_scan: false
    trusted_servers:
      - "localhost:3000"
      - "localhost:3001"
      - "localhost:3002"
    scan_interval: 300  # seconds
    max_servers: 50

# Policy Engine Configuration
policy_engine:
  default_policies: true
  policy_file: "policies/default_policies.yaml"
  evaluation_timeout: 5.0  # seconds
  cache_policies: true
  cache_size: 1000
  policy_update_interval: 300  # seconds
  enable_audit_logging: true

# Tool Registry Configuration
tool_registry:
  auto_register: true
  verification_required: true
  attestation_required: true
  max_tools_per_agent: 50
  max_tool_versions: 10
  cleanup_interval: 3600  # seconds
  enable_usage_tracking: true

# Logging Configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  audit_logging: true
  security_events: true
  log_file: "logs/security.log"
  audit_file: "logs/audit.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5
  console_output: true
  structured_logging: true

# Cryptography Configuration
cryptography:
  key_size: 2048  # 1024, 2048, 3072, 4096
  hash_algorithm: SHA256  # SHA256, SHA512
  signature_algorithm: RSA-PSS  # RSA-PSS, RSA-PKCS1
  encryption_algorithm: AES-256-GCM  # AES-256-GCM, AES-256-CBC
  key_rotation_interval: 86400  # seconds (24 hours)
  certificate_validity_days: 365

# MAS Adapters Configuration
mas_adapters:
  langgraph:
    enabled: true
    workflow_security: true
    node_verification: true
    execution_timeout: 300  # seconds
    max_concurrent_workflows: 10
  
  autogen:
    enabled: true
    conversation_security: true
    message_encryption: true
    conversation_timeout: 1800  # seconds
    max_conversation_participants: 20
  
  crewai:
    enabled: true
    crew_verification: true
    task_security: true
    crew_timeout: 3600  # seconds
    max_crew_members: 15

# Performance Configuration
performance:
  max_concurrent_operations: 100
  operation_timeout: 30.0  # seconds
  cache_size: 1000
  cleanup_interval: 3600  # seconds
  memory_limit: 1073741824  # 1GB
  cpu_limit: 80  # percentage

# Security Configuration
security:
  rate_limiting:
    enabled: true
    max_requests_per_minute: 100
    max_requests_per_hour: 1000
    max_requests_per_day: 10000
    rate_limit_window: 60  # seconds
  
  threat_detection:
    enabled: true
    anomaly_detection: true
    pattern_analysis: true
    real_time_monitoring: true
    alert_threshold: 0.8
    auto_response: false
  
  monitoring:
    enabled: true
    metrics_collection: true
    health_checks: true
    performance_monitoring: true
    alert_threshold: 0.8
    notification_channels: []  # email, slack, webhook
  
  access_control:
    default_deny: true
    require_explicit_permissions: true
    enable_role_based_access: true
    enable_capability_based_access: true
    enable_attribute_based_access: true

# Network Configuration
network:
  bind_address: "0.0.0.0"
  port: 8080
  ssl_enabled: false
  ssl_cert_file: ""
  ssl_key_file: ""
  cors_enabled: true
  cors_origins: ["*"]
  max_request_size: 10485760  # 10MB

# Database Configuration (if using persistent storage)
database:
  enabled: false
  type: "sqlite"  # sqlite, postgresql, mysql
  connection_string: "sqlite:///mcp_security.db"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# External Services Configuration
external_services:
  certificate_authority:
    enabled: false
    url: ""
    api_key: ""
    timeout: 30
  
  threat_intelligence:
    enabled: false
    providers: []  # virustotal, abuseipdb, etc.
    api_keys: {}
    update_interval: 3600
  
  notification_service:
    enabled: false
    type: "email"  # email, slack, webhook
    config: {}
    retry_attempts: 3
    retry_delay: 60